# Generated by Django 5.1.4 on 2024-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('path_saved_order', models.CharField(max_length=255, verbose_name='Папка сохранения заявок XML')),
                ('path_saved_reports', models.CharField(max_length=255, verbose_name='Папка сохранения отчетов')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('id_groups_goods', models.IntegerField(default=0, verbose_name='Код папки товаров')),
                ('id_postav', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код поставщика')),
                ('id_client', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код клиента')),
                ('id_sklad', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код склада')),
                ('id_agent', models.IntegerField(blank=True, default=0, null=True, verbose_name='Код агента')),
                ('filial', models.ManyToManyField(related_name='contracts', to='base_app.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ('position',),
            },
        ),
    ]
