# Generated by Django 5.1.4 on 2024-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_contracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='path_saved_order',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='path_saved_reports',
        ),
        migrations.AddField(
            model_name='filial',
            name='path_saved_order',
            field=models.CharField(default='/', max_length=255, verbose_name='Папка сохранения заявок XML'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='path_saved_reports',
            field=models.CharField(default='/', max_length=255, verbose_name='Папка сохранения отчетов'),
            preserve_default=False,
        ),
    ]
