# Generated by Django 5.1.4 on 2024-12-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_remove_filial_path_saved_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='filial',
        ),
        migrations.AddField(
            model_name='contracts',
            name='menu',
            field=models.ManyToManyField(related_name='contracts', to='base_app.menu', verbose_name='Филиал'),
        ),
    ]
