# Generated by Django 5.1.4 on 2024-12-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_remove_contracts_filial_contracts_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='filial',
            field=models.ManyToManyField(related_name='contracts', to='base_app.filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='menu',
            field=models.ManyToManyField(related_name='contracts', to='base_app.menu', verbose_name='Меню'),
        ),
    ]
