# Generated by Django 5.1.4 on 2024-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_contracts_filial_alter_contracts_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция в меню')),
                ('as_active', models.BooleanField(default=True, verbose_name='Признак активности')),
                ('menu', models.ManyToManyField(related_name='menus', to='base_app.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='contracts',
            name='submenu',
            field=models.ManyToManyField(related_name='contracts', to='base_app.submenu', verbose_name='Операция'),
        ),
    ]
