# Generated by Django 5.1.4 on 2024-12-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_alter_submenu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('filial', models.ManyToManyField(related_name='tests', to='base_app.filial', verbose_name='Филиал')),
            ],
        ),
    ]
